name: Update requirements.txt

on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python (via uv)
        run: uv python install

      - name: Export requirements.txt
        run: uv export --no-emit-workspace --no-dev --no-annotate --no-header --no-hashes --output-file requirements.txt

      - name: Commit and push requirements.txt if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt
          if git diff --cached --quiet; then
            echo "No changes to requirements.txt"
            exit 0
          fi
          git commit -m "chore: update requirements.txt (uv export)" --no-verify
          git push origin HEAD:main
